Repository JulianPedro/mindminer, pull requests merged in 2021-09, with the labels that each got.

#22 Fix #21: Criar task para iniciar o crawling de acordo com os assuntos mais populares
  crawler/docker-compose.yml
  crawler/scrapy/mindminer/scrapy.cfg
  main/backend/django/mindminer/settings.py
  main/backend/django/subject/crawler_client.py
  main/backend/django/subject/tasks.py
  main/backend/env/main.env
Labels: crawler, backend

#19 WIP #8: Desenvolvimento Frontend
  main/backend/django/subject/views.py
  main/docker-compose.yml
  main/frontend/assets/css/tailwind.css
  main/frontend/components/global/mm-paginate.vue
  main/frontend/components/global/mm-sort.vue
  main/frontend/components/layout/header/mm-header.vue
  main/frontend/components/layout/header/mm-hearder-search-bar.vue
  main/frontend/components/pages/details/mm-details-subject-title.vue
  main/frontend/components/pages/details/mm-details-tweet-comment.vue
  main/frontend/components/pages/details/mm-subject-text.vue
  main/frontend/components/pages/home/mm-home-main.vue
  main/frontend/components/pages/home/mm-home-sidebar.vue
  main/frontend/components/pages/home/mm-subject.vue
  main/frontend/layouts/default.vue
  main/frontend/nuxt.config.js
  main/frontend/package.json
  main/frontend/pages/details/_id.vue
  main/frontend/pages/index.vue
  main/frontend/pages/search.vue
  main/frontend/plugins/eChart.js
  main/frontend/plugins/moment.js
  main/frontend/plugins/vueCarousel.js
  main/frontend/tailwind.config.js
Labels: frontend

#23 Corrigido alguns problemas
  main/frontend/components/layout/header/mm-header.vue
  main/frontend/components/pages/details/mm-subject-text.vue
  main/frontend/components/pages/home/mm-subject.vue
  main/frontend/pages/details/_id.vue
  main/frontend/pages/search.vue
  main/frontend/static/favicon.ico
Labels: bug

#24 Configurado env
  main/frontend/.env.example
  main/frontend/nuxt.config.js
Labels: enhancement

#25 Filtro de tweets
  main/frontend/components/pages/home/mm-home-main.vue
  main/frontend/components/pages/home/mm-home-sidebar.vue
  main/frontend/nuxt.config.js
  main/frontend/package.json
  main/frontend/pages/details/_id.vue
  main/frontend/pages/search.vue
  main/frontend/plugins/vueDatePicker.js
Labels: enhancement

#26 Criado página de versionamento
  main/frontend/components/pages/details/mm-subject-text.vue
  main/frontend/pages/releases.vue
Labels: enhancement
